
name: Hello, world!

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:

      - name: Run a one-line script
        run: echo Hello, world!
