---
name: Install apt packages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  # https://ourcodeworld.com/articles/read/1409/how-to-use-musescore-3-in-headless-mode-in-ubuntu-2004
  QT_QPA_PLATFORM: offscreen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Install “musescore3”
        run: sudo apt install musescore3
      - name: List installed files of the package “musescore3”
        run: dpkg -L musescore3
      - name: Show version of the installed package “/usr/bin/mscore3”
        run: mscore3 --version
      - name: Download latest “mscore4” AppImage
        run: |
          wget -O mscore4 https://github.com/musescore/MuseScore/releases/download/v4.2.0/MuseScore-4.2.0.233521125-x86_64.AppImage
          chmod a+x mscore4
          sudo apt install libfuse2
          ./mscore4 --version
          sudo cp mscore4 /usr/bin/mscore4

      - name: Run previous installed mscore4
        run: |
          /usr/bin/mscore4 --version
          mscore4 --version
