name: Install apt packages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Install “musescore3”
        run: sudo apt install musescore3
      - name: List installed files of the package “musescore3”
        run: dpkg -L musescore3
      - name: Show version of the installed package “/usr/bin/mscore3”
        run: mscore3 --version
