---
name: Install AppImage

on:
  workflow_dispatch:

env:
  # https://github.com/musescore/MuseScore/issues/17247
  # https://ourcodeworld.com/articles/read/1409/how-to-use-musescore-3-in-headless-mode-in-ubuntu-2004
  QT_QPA_PLATFORM: offscreen

jobs:
  install_app_image:
    runs-on: ubuntu-latest

    steps:

      - name: >-
          Install “libfuse2” to prevent an error like: error
          while loading shared libraries: libfuse.so.2: cannot open shared
          object file: No such file or directory
        run: sudo apt install libfuse2
      - name: Download latest “mscore4” AppImage
        run: |
          wget --quiet --output-document mscore4 https://github.com/musescore/MuseScore/releases/download/v4.2.0/MuseScore-4.2.0.233521125-x86_64.AppImage
          chmod a+x mscore4
          sudo cp mscore4 /usr/bin/mscore4

      - name: Show version of previous installed “mscore4”
        run: |
          mscore4 --version
